Exit early when the tarball is for a version that was published.

diff --git a/publish-revision b/publish-revision
--- a/publish-revision
+++ b/publish-revision
@@ -6,6 +6,12 @@ BUILD_PACKAGES=${BUILD_PACKAGES:-true}
 TARFILE=$($SCRIPTS/get-tarfile-name)
 VERSION=$(basename $TARFILE .tar.gz | cut -d '_' -f2)
 
+if [[ -f " $LOCAL_TOOLS_CACHE/juju-$VERSION-trusty-amd64.tgz" ]]; then
+    echo "$VERSION was published. This version is invalid to test."
+    echo "Maybe juju's version needs updating?"
+    exit 1
+fi
+
 if [[ $BUILD_PACKAGES == 'true' ]]; then
 wget -q $LOCAL_JENKINS_URL/job/build-revision/lastSuccessfulBuild/artifact/$TARFILE
 
