Ensure that we don't have any panics

diff --git a/.github/workflows/upgrade.yml b/.github/workflows/upgrade.yml
--- a/.github/workflows/upgrade.yml
+++ b/.github/workflows/upgrade.yml
@@ -48,4 +48,19 @@ jobs:
       shell: bash
       run: |
         set -euxo pipefail
+        CURRENT=$(juju status --format=json 2>/dev/null | jq -r ".model | .version")
+
         juju upgrade-controller --build-agent
+
+        UPDATED=$(juju status --format=json 2>/dev/null | jq -r ".model | .version")
+        if [ "$CURRENT" == "$UPDATED" ]; then
+            echo "Upgrade failure"
+            exit 1
+        fi
+
+        PANIC=$(juju debug-log --replay --no-tail -m controller | grep "panic" | wc -m)
+        if [ "$PANIC" -ne 0 ]; then
+            echo "Panic found:"
+            juju debug-log --replay --no-tail -m controller
+            exit 1
+        fi
